### PR TITLE
FP-3007: Scene - Search backspace on drawer deletes node

### PR DESCRIPTION
**Pull request by quirinpa**
- [FP-3001](https://movai.atlassian.net/browse/FP-3001): Clicking backspace on drawer input deletes selected node

- This also make save a global keybind to avoid the shortcut not working with modal or drawer focus
- The branch name was wrong, and this mentioned the scene, which was also an error in part. Although this affects the scene as well, the original ticket did not reference the scene editor.

[FP-3007]: https://movai.atlassian.net/browse/FP-3007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FP-3001]: https://movai.atlassian.net/browse/FP-3001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by manuelnogueiramov — CHANGES_REQUESTED** [review]
I don't like that we are overriding the default behaviour of the browser. If for some reason we later have a modal that needs to use the ctrl+s keybind, or if the user just simply wants to save the page's HTML, we are preventing that from happening MORE than we should. I mean, we already do that when we are on a file, but why do it everywhere? We just want to save if we are on a file...

**Comment by quirinpa** [comment]
So it would be preferable to not override the default behavior of the browser just when you're focusing a drawer? Not very intuitive.

Why wasn't this an issue before? IDE is full of vanilla disablement.

**Comment by diasnad** [comment]
On last Thursday (October 31), on our team meeting it was discussed this solution for the issue of not saving the node or flow when the user was focus on the drawer (https://github.com/MOV-AI/frontend-npm-lib-ide/pull/368) and in the end of the meeting we concluded that removing crtl+s of the browser wasn't the best solution

**Comment by quirinpa** [comment]
We should find the beginning before the end.

**Comment by diasnad** [comment]
As we discussed in a meeting today, since in previous versions the crtl+s of the browser was off, we will approve this PR, although for future versions this needs to be discussed

**Review by diasnad — APPROVED** [review]

**Review by manuelnogueiramov — APPROVED** [review]

**Pull request merged**
